### ISSUE TITLE
Enforce FIFO order

### ISSUE THREAD

**Issue by Type-kun** [r888888888/archives#6]
I vaguely remember @r888888888 mentioning there's no guarantee that messages will get delivered/processed in order they were pushed. Due to the nature of versioning service this spells disaster, because if two versions for the same post get delivered out of order, the diffs will get calculated and stored incorrectly.

Some thoughts:
1) AWS supports FIFO mode as far as I can tell, they advertise it on their front page; it should be enabled if it isn't already
2) Version ID can be generated from a sequence on a main danbooru site and pushed to the queue as well. That way, if versions get delivered out of order, we at least have a chance of reordering everything properly: calculate diff to the nearest prior version and recalculate all diffs for later versions. Version merging would interfere, though, so it's best to make sure that queue is processed in order.

**Comment by r888888888** [comment]
I've created new fifo queues.

**Comment by evazion** [comment]
@r888888888 

Uploads/tag edits are giving the error below. Related to the FIFO queues?

```
Aws::SQS::Errors::MissingParameter exception raised
The request must contain the parameter MessageGroupId.
app/logical/sqs_service.rb:15:in `send_message'
app/models/post_archive.rb:77:in `queue'
app/models/post.rb:1474:in `create_new_version'
app/models/post.rb:1463:in `create_version'
app/controllers/posts_controller.rb:49:in `update'
```
